---
# tasks file for masterrole
 - name: Installing docker package
   package: 
         name: docker
         state: present
 - name: Starting docker services
   service:
         name: docker
         enabled: yes
 - name: Configuring repo for kubelet
   template:
         src: kube.repo
         dest: /etc/yum.repos.d/kubernetes.repo
 - name: Installing kubelet
   shell:
         cmd: yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
 - name: Starting kubelet services
   service:
         name: kubelet
         state: started
         enabled: yes
 - name: Setting up systemd driver(docker)
   template:
         src: daemon.json
         dest: /etc/docker/daemon.json
 - name: Restarting docker services
   service:
           name: docker
           state: restarted
 - name: Installing iproute-tc package
   package:
         name: iproute-tc
         state: present
 - name: Installing kubelet
   shell: yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
   register: y
 - debug: 
      var: y
 - name: Starting the kubelet services
   service:
           name: kubelet
           state: started
           enabled: yes
 - name: Enabling bridge network
   template:
         src: k8s.conf
         dest: /etc/sysctl.d/k8s.conf
 - name: Reloading the system
   shell:
         cmd: sysctl --system

       
